# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f1d01ff21dcbf9b6ea9a19b7ee309007cbb29aaf595c4ddee80affc0eb2564597b5b0cac7fa52147181f300e4868707e2faa1752da12decbf635da68fac80dc3

test:
  secret_key_base: 5b9f7954881c319aaf8cbea5ec09ad4fb935c1d893c59ded68a81885704d34fd04dda5c5206faee2701a4e336c695253a3f5c2662bee3da697d9a8f4da997163

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
